name: Gr(iN)
favicon: null
layout_spectrum: 0.30721786548383534
typography_spectrum: 0.007476387545466423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6162274826783687
  lightness: 0.5603670214768499
  saturation: 0.528302957303822
  rhythmicContrast: 0.2191763953305781
purpose: []
